-- 001_init.down.sql
DROP TABLE IF EXISTS ai_suggestions;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS goals;
DROP TABLE IF EXISTS users;